/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.msg.MsgSnakePlayer');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.msg.MsgSnakePlayer = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.msg.MsgSnakePlayer, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.msg.MsgSnakePlayer.displayName = 'proto.msg.MsgSnakePlayer';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.msg.MsgSnakePlayer.prototype.toObject = function(opt_includeInstance) {
  return proto.msg.MsgSnakePlayer.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.msg.MsgSnakePlayer} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg.MsgSnakePlayer.toObject = function(includeInstance, msg) {
  var f, obj = {
    uid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    nickname: jspb.Message.getFieldWithDefault(msg, 2, ""),
    faceurl: jspb.Message.getFieldWithDefault(msg, 3, ""),
    frameid: jspb.Message.getFieldWithDefault(msg, 4, ""),
    signname: jspb.Message.getFieldWithDefault(msg, 5, ""),
    sex: jspb.Message.getFieldWithDefault(msg, 6, 0),
    gold: +jspb.Message.getFieldWithDefault(msg, 7, 0.0),
    goldbig: +jspb.Message.getFieldWithDefault(msg, 8, 0.0),
    teamscore: jspb.Message.getFieldWithDefault(msg, 9, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.msg.MsgSnakePlayer}
 */
proto.msg.MsgSnakePlayer.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.msg.MsgSnakePlayer;
  return proto.msg.MsgSnakePlayer.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.msg.MsgSnakePlayer} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.msg.MsgSnakePlayer}
 */
proto.msg.MsgSnakePlayer.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNickname(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setFaceurl(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setFrameid(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setSignname(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSex(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setGold(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setGoldbig(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTeamscore(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.msg.MsgSnakePlayer.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.msg.MsgSnakePlayer.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.msg.MsgSnakePlayer} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg.MsgSnakePlayer.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUid();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getNickname();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getFaceurl();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getFrameid();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getSignname();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getSex();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getGold();
  if (f !== 0.0) {
    writer.writeDouble(
      7,
      f
    );
  }
  f = message.getGoldbig();
  if (f !== 0.0) {
    writer.writeDouble(
      8,
      f
    );
  }
  f = message.getTeamscore();
  if (f !== 0) {
    writer.writeInt64(
      9,
      f
    );
  }
};


/**
 * optional int64 UID = 1;
 * @return {number}
 */
proto.msg.MsgSnakePlayer.prototype.getUid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.msg.MsgSnakePlayer.prototype.setUid = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string Nickname = 2;
 * @return {string}
 */
proto.msg.MsgSnakePlayer.prototype.getNickname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.msg.MsgSnakePlayer.prototype.setNickname = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string Faceurl = 3;
 * @return {string}
 */
proto.msg.MsgSnakePlayer.prototype.getFaceurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.msg.MsgSnakePlayer.prototype.setFaceurl = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string FrameID = 4;
 * @return {string}
 */
proto.msg.MsgSnakePlayer.prototype.getFrameid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.msg.MsgSnakePlayer.prototype.setFrameid = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string Signname = 5;
 * @return {string}
 */
proto.msg.MsgSnakePlayer.prototype.getSignname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.msg.MsgSnakePlayer.prototype.setSignname = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional int32 Sex = 6;
 * @return {number}
 */
proto.msg.MsgSnakePlayer.prototype.getSex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.msg.MsgSnakePlayer.prototype.setSex = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional double Gold = 7;
 * @return {number}
 */
proto.msg.MsgSnakePlayer.prototype.getGold = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 7, 0.0));
};


/** @param {number} value */
proto.msg.MsgSnakePlayer.prototype.setGold = function(value) {
  jspb.Message.setProto3FloatField(this, 7, value);
};


/**
 * optional double GoldBig = 8;
 * @return {number}
 */
proto.msg.MsgSnakePlayer.prototype.getGoldbig = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 8, 0.0));
};


/** @param {number} value */
proto.msg.MsgSnakePlayer.prototype.setGoldbig = function(value) {
  jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * optional int64 TeamScore = 9;
 * @return {number}
 */
proto.msg.MsgSnakePlayer.prototype.getTeamscore = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {number} value */
proto.msg.MsgSnakePlayer.prototype.setTeamscore = function(value) {
  jspb.Message.setProto3IntField(this, 9, value);
};


