/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.msg.MsgSnakeDeskRet');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.msg.MsgSnakePlayer');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.msg.MsgSnakeDeskRet = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.msg.MsgSnakeDeskRet.repeatedFields_, null);
};
goog.inherits(proto.msg.MsgSnakeDeskRet, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.msg.MsgSnakeDeskRet.displayName = 'proto.msg.MsgSnakeDeskRet';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.msg.MsgSnakeDeskRet.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.msg.MsgSnakeDeskRet.prototype.toObject = function(opt_includeInstance) {
  return proto.msg.MsgSnakeDeskRet.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.msg.MsgSnakeDeskRet} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg.MsgSnakeDeskRet.toObject = function(includeInstance, msg) {
  var f, obj = {
    self: (f = msg.getSelf()) && proto.msg.MsgSnakePlayer.toObject(includeInstance, f),
    skillid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    skinid: jspb.Message.getFieldWithDefault(msg, 3, 0),
    srvtime: jspb.Message.getFieldWithDefault(msg, 4, 0),
    playersList: jspb.Message.toObjectList(msg.getPlayersList(),
    proto.msg.MsgSnakePlayer.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.msg.MsgSnakeDeskRet}
 */
proto.msg.MsgSnakeDeskRet.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.msg.MsgSnakeDeskRet;
  return proto.msg.MsgSnakeDeskRet.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.msg.MsgSnakeDeskRet} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.msg.MsgSnakeDeskRet}
 */
proto.msg.MsgSnakeDeskRet.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.msg.MsgSnakePlayer;
      reader.readMessage(value,proto.msg.MsgSnakePlayer.deserializeBinaryFromReader);
      msg.setSelf(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSkillid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSkinid(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSrvtime(value);
      break;
    case 5:
      var value = new proto.msg.MsgSnakePlayer;
      reader.readMessage(value,proto.msg.MsgSnakePlayer.deserializeBinaryFromReader);
      msg.addPlayers(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.msg.MsgSnakeDeskRet.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.msg.MsgSnakeDeskRet.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.msg.MsgSnakeDeskRet} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg.MsgSnakeDeskRet.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSelf();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.msg.MsgSnakePlayer.serializeBinaryToWriter
    );
  }
  f = message.getSkillid();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getSkinid();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getSrvtime();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getPlayersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.msg.MsgSnakePlayer.serializeBinaryToWriter
    );
  }
};


/**
 * optional MsgSnakePlayer Self = 1;
 * @return {?proto.msg.MsgSnakePlayer}
 */
proto.msg.MsgSnakeDeskRet.prototype.getSelf = function() {
  return /** @type{?proto.msg.MsgSnakePlayer} */ (
    jspb.Message.getWrapperField(this, proto.msg.MsgSnakePlayer, 1));
};


/** @param {?proto.msg.MsgSnakePlayer|undefined} value */
proto.msg.MsgSnakeDeskRet.prototype.setSelf = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.msg.MsgSnakeDeskRet.prototype.clearSelf = function() {
  this.setSelf(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.msg.MsgSnakeDeskRet.prototype.hasSelf = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 Skillid = 2;
 * @return {number}
 */
proto.msg.MsgSnakeDeskRet.prototype.getSkillid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.msg.MsgSnakeDeskRet.prototype.setSkillid = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 Skinid = 3;
 * @return {number}
 */
proto.msg.MsgSnakeDeskRet.prototype.getSkinid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.msg.MsgSnakeDeskRet.prototype.setSkinid = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int64 SrvTime = 4;
 * @return {number}
 */
proto.msg.MsgSnakeDeskRet.prototype.getSrvtime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.msg.MsgSnakeDeskRet.prototype.setSrvtime = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * repeated MsgSnakePlayer Players = 5;
 * @return {!Array<!proto.msg.MsgSnakePlayer>}
 */
proto.msg.MsgSnakeDeskRet.prototype.getPlayersList = function() {
  return /** @type{!Array<!proto.msg.MsgSnakePlayer>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.msg.MsgSnakePlayer, 5));
};


/** @param {!Array<!proto.msg.MsgSnakePlayer>} value */
proto.msg.MsgSnakeDeskRet.prototype.setPlayersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.msg.MsgSnakePlayer=} opt_value
 * @param {number=} opt_index
 * @return {!proto.msg.MsgSnakePlayer}
 */
proto.msg.MsgSnakeDeskRet.prototype.addPlayers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.msg.MsgSnakePlayer, opt_index);
};


proto.msg.MsgSnakeDeskRet.prototype.clearPlayersList = function() {
  this.setPlayersList([]);
};


