/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.msg.MsgSnakeEndGameResultRet');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.msg.ModeEndAwardConf');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.msg.MsgSnakeEndGameResultRet = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.msg.MsgSnakeEndGameResultRet, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.msg.MsgSnakeEndGameResultRet.displayName = 'proto.msg.MsgSnakeEndGameResultRet';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.msg.MsgSnakeEndGameResultRet.prototype.toObject = function(opt_includeInstance) {
  return proto.msg.MsgSnakeEndGameResultRet.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.msg.MsgSnakeEndGameResultRet} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg.MsgSnakeEndGameResultRet.toObject = function(includeInstance, msg) {
  var f, obj = {
    conf: (f = msg.getConf()) && proto.msg.ModeEndAwardConf.toObject(includeInstance, f),
    snakelen: jspb.Message.getFieldWithDefault(msg, 2, 0),
    snakelengold: +jspb.Message.getFieldWithDefault(msg, 3, 0.0),
    daysnakelen: jspb.Message.getFieldWithDefault(msg, 4, 0),
    daygetgoldlen: jspb.Message.getFieldWithDefault(msg, 5, 0),
    daysnakelenwin: +jspb.Message.getFieldWithDefault(msg, 6, 0.0),
    killnum: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.msg.MsgSnakeEndGameResultRet}
 */
proto.msg.MsgSnakeEndGameResultRet.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.msg.MsgSnakeEndGameResultRet;
  return proto.msg.MsgSnakeEndGameResultRet.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.msg.MsgSnakeEndGameResultRet} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.msg.MsgSnakeEndGameResultRet}
 */
proto.msg.MsgSnakeEndGameResultRet.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.msg.ModeEndAwardConf;
      reader.readMessage(value,proto.msg.ModeEndAwardConf.deserializeBinaryFromReader);
      msg.setConf(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSnakelen(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setSnakelengold(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDaysnakelen(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDaygetgoldlen(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setDaysnakelenwin(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setKillnum(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.msg.MsgSnakeEndGameResultRet.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.msg.MsgSnakeEndGameResultRet.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.msg.MsgSnakeEndGameResultRet} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg.MsgSnakeEndGameResultRet.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getConf();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.msg.ModeEndAwardConf.serializeBinaryToWriter
    );
  }
  f = message.getSnakelen();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getSnakelengold();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getDaysnakelen();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getDaygetgoldlen();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getDaysnakelenwin();
  if (f !== 0.0) {
    writer.writeDouble(
      6,
      f
    );
  }
  f = message.getKillnum();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
};


/**
 * optional ModeEndAwardConf conf = 1;
 * @return {?proto.msg.ModeEndAwardConf}
 */
proto.msg.MsgSnakeEndGameResultRet.prototype.getConf = function() {
  return /** @type{?proto.msg.ModeEndAwardConf} */ (
    jspb.Message.getWrapperField(this, proto.msg.ModeEndAwardConf, 1));
};


/** @param {?proto.msg.ModeEndAwardConf|undefined} value */
proto.msg.MsgSnakeEndGameResultRet.prototype.setConf = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.msg.MsgSnakeEndGameResultRet.prototype.clearConf = function() {
  this.setConf(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.msg.MsgSnakeEndGameResultRet.prototype.hasConf = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 SnakeLen = 2;
 * @return {number}
 */
proto.msg.MsgSnakeEndGameResultRet.prototype.getSnakelen = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.msg.MsgSnakeEndGameResultRet.prototype.setSnakelen = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional double SnakeLenGold = 3;
 * @return {number}
 */
proto.msg.MsgSnakeEndGameResultRet.prototype.getSnakelengold = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 3, 0.0));
};


/** @param {number} value */
proto.msg.MsgSnakeEndGameResultRet.prototype.setSnakelengold = function(value) {
  jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional int32 DaySnakeLen = 4;
 * @return {number}
 */
proto.msg.MsgSnakeEndGameResultRet.prototype.getDaysnakelen = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.msg.MsgSnakeEndGameResultRet.prototype.setDaysnakelen = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 DayGetGoldLen = 5;
 * @return {number}
 */
proto.msg.MsgSnakeEndGameResultRet.prototype.getDaygetgoldlen = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.msg.MsgSnakeEndGameResultRet.prototype.setDaygetgoldlen = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional double DaySnakeLenWin = 6;
 * @return {number}
 */
proto.msg.MsgSnakeEndGameResultRet.prototype.getDaysnakelenwin = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 6, 0.0));
};


/** @param {number} value */
proto.msg.MsgSnakeEndGameResultRet.prototype.setDaysnakelenwin = function(value) {
  jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional int32 KillNum = 7;
 * @return {number}
 */
proto.msg.MsgSnakeEndGameResultRet.prototype.getKillnum = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.msg.MsgSnakeEndGameResultRet.prototype.setKillnum = function(value) {
  jspb.Message.setProto3IntField(this, 7, value);
};


