/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.msg.MsgNotifyGoldChgRet');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.msg.MsgNotifyGoldChgRet = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.msg.MsgNotifyGoldChgRet, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.msg.MsgNotifyGoldChgRet.displayName = 'proto.msg.MsgNotifyGoldChgRet';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.msg.MsgNotifyGoldChgRet.prototype.toObject = function(opt_includeInstance) {
  return proto.msg.MsgNotifyGoldChgRet.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.msg.MsgNotifyGoldChgRet} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg.MsgNotifyGoldChgRet.toObject = function(includeInstance, msg) {
  var f, obj = {
    uid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    gold: +jspb.Message.getFieldWithDefault(msg, 2, 0.0),
    goldbig: +jspb.Message.getFieldWithDefault(msg, 3, 0.0),
    teamscore: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.msg.MsgNotifyGoldChgRet}
 */
proto.msg.MsgNotifyGoldChgRet.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.msg.MsgNotifyGoldChgRet;
  return proto.msg.MsgNotifyGoldChgRet.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.msg.MsgNotifyGoldChgRet} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.msg.MsgNotifyGoldChgRet}
 */
proto.msg.MsgNotifyGoldChgRet.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setGold(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setGoldbig(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTeamscore(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.msg.MsgNotifyGoldChgRet.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.msg.MsgNotifyGoldChgRet.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.msg.MsgNotifyGoldChgRet} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg.MsgNotifyGoldChgRet.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUid();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getGold();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getGoldbig();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getTeamscore();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
};


/**
 * optional int64 UID = 1;
 * @return {number}
 */
proto.msg.MsgNotifyGoldChgRet.prototype.getUid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.msg.MsgNotifyGoldChgRet.prototype.setUid = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional double Gold = 2;
 * @return {number}
 */
proto.msg.MsgNotifyGoldChgRet.prototype.getGold = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 2, 0.0));
};


/** @param {number} value */
proto.msg.MsgNotifyGoldChgRet.prototype.setGold = function(value) {
  jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional double GoldBig = 3;
 * @return {number}
 */
proto.msg.MsgNotifyGoldChgRet.prototype.getGoldbig = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 3, 0.0));
};


/** @param {number} value */
proto.msg.MsgNotifyGoldChgRet.prototype.setGoldbig = function(value) {
  jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional int64 TeamScore = 4;
 * @return {number}
 */
proto.msg.MsgNotifyGoldChgRet.prototype.getTeamscore = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.msg.MsgNotifyGoldChgRet.prototype.setTeamscore = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


