/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.msg.LoginResp');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.msg.LoginResp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.msg.LoginResp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.msg.LoginResp.displayName = 'proto.msg.LoginResp';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.msg.LoginResp.prototype.toObject = function(opt_includeInstance) {
  return proto.msg.LoginResp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.msg.LoginResp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg.LoginResp.toObject = function(includeInstance, msg) {
  var f, obj = {
    uid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    nickname: jspb.Message.getFieldWithDefault(msg, 2, ""),
    faceurl: jspb.Message.getFieldWithDefault(msg, 3, ""),
    frameid: jspb.Message.getFieldWithDefault(msg, 4, 0),
    signname: jspb.Message.getFieldWithDefault(msg, 5, ""),
    sex: jspb.Message.getFieldWithDefault(msg, 6, 0),
    inviteid: jspb.Message.getFieldWithDefault(msg, 7, 0),
    gold: +jspb.Message.getFieldWithDefault(msg, 10, 0.0),
    goldbig: +jspb.Message.getFieldWithDefault(msg, 11, 0.0),
    teamscore: jspb.Message.getFieldWithDefault(msg, 12, 0),
    token: jspb.Message.getFieldWithDefault(msg, 15, ""),
    gateinfo: jspb.Message.getFieldWithDefault(msg, 16, ""),
    firstlogin: jspb.Message.getFieldWithDefault(msg, 17, 0),
    srvtime: jspb.Message.getFieldWithDefault(msg, 18, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.msg.LoginResp}
 */
proto.msg.LoginResp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.msg.LoginResp;
  return proto.msg.LoginResp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.msg.LoginResp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.msg.LoginResp}
 */
proto.msg.LoginResp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNickname(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setFaceurl(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFrameid(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setSignname(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSex(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setInviteid(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setGold(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setGoldbig(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTeamscore(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setToken(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setGateinfo(value);
      break;
    case 17:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFirstlogin(value);
      break;
    case 18:
      var value = /** @type {string} */ (reader.readString());
      msg.setSrvtime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.msg.LoginResp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.msg.LoginResp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.msg.LoginResp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg.LoginResp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUid();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getNickname();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getFaceurl();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getFrameid();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getSignname();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getSex();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getInviteid();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getGold();
  if (f !== 0.0) {
    writer.writeDouble(
      10,
      f
    );
  }
  f = message.getGoldbig();
  if (f !== 0.0) {
    writer.writeDouble(
      11,
      f
    );
  }
  f = message.getTeamscore();
  if (f !== 0) {
    writer.writeInt64(
      12,
      f
    );
  }
  f = message.getToken();
  if (f.length > 0) {
    writer.writeString(
      15,
      f
    );
  }
  f = message.getGateinfo();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
  f = message.getFirstlogin();
  if (f !== 0) {
    writer.writeInt32(
      17,
      f
    );
  }
  f = message.getSrvtime();
  if (f.length > 0) {
    writer.writeString(
      18,
      f
    );
  }
};


/**
 * optional int64 UID = 1;
 * @return {number}
 */
proto.msg.LoginResp.prototype.getUid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.msg.LoginResp.prototype.setUid = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string NickName = 2;
 * @return {string}
 */
proto.msg.LoginResp.prototype.getNickname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.msg.LoginResp.prototype.setNickname = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string FaceUrl = 3;
 * @return {string}
 */
proto.msg.LoginResp.prototype.getFaceurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.msg.LoginResp.prototype.setFaceurl = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int32 FrameID = 4;
 * @return {number}
 */
proto.msg.LoginResp.prototype.getFrameid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.msg.LoginResp.prototype.setFrameid = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string SignName = 5;
 * @return {string}
 */
proto.msg.LoginResp.prototype.getSignname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.msg.LoginResp.prototype.setSignname = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional int32 Sex = 6;
 * @return {number}
 */
proto.msg.LoginResp.prototype.getSex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.msg.LoginResp.prototype.setSex = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int32 InviteID = 7;
 * @return {number}
 */
proto.msg.LoginResp.prototype.getInviteid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.msg.LoginResp.prototype.setInviteid = function(value) {
  jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional double Gold = 10;
 * @return {number}
 */
proto.msg.LoginResp.prototype.getGold = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 10, 0.0));
};


/** @param {number} value */
proto.msg.LoginResp.prototype.setGold = function(value) {
  jspb.Message.setProto3FloatField(this, 10, value);
};


/**
 * optional double GoldBig = 11;
 * @return {number}
 */
proto.msg.LoginResp.prototype.getGoldbig = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 11, 0.0));
};


/** @param {number} value */
proto.msg.LoginResp.prototype.setGoldbig = function(value) {
  jspb.Message.setProto3FloatField(this, 11, value);
};


/**
 * optional int64 TeamScore = 12;
 * @return {number}
 */
proto.msg.LoginResp.prototype.getTeamscore = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/** @param {number} value */
proto.msg.LoginResp.prototype.setTeamscore = function(value) {
  jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional string Token = 15;
 * @return {string}
 */
proto.msg.LoginResp.prototype.getToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/** @param {string} value */
proto.msg.LoginResp.prototype.setToken = function(value) {
  jspb.Message.setProto3StringField(this, 15, value);
};


/**
 * optional string GateInfo = 16;
 * @return {string}
 */
proto.msg.LoginResp.prototype.getGateinfo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/** @param {string} value */
proto.msg.LoginResp.prototype.setGateinfo = function(value) {
  jspb.Message.setProto3StringField(this, 16, value);
};


/**
 * optional int32 FirstLogin = 17;
 * @return {number}
 */
proto.msg.LoginResp.prototype.getFirstlogin = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 17, 0));
};


/** @param {number} value */
proto.msg.LoginResp.prototype.setFirstlogin = function(value) {
  jspb.Message.setProto3IntField(this, 17, value);
};


/**
 * optional string SrvTime = 18;
 * @return {string}
 */
proto.msg.LoginResp.prototype.getSrvtime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 18, ""));
};


/** @param {string} value */
proto.msg.LoginResp.prototype.setSrvtime = function(value) {
  jspb.Message.setProto3StringField(this, 18, value);
};


