/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.msg.RoomListResp');
goog.provide('proto.msg.RoomListResp.RoomItem');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.msg.RoomListResp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.msg.RoomListResp.repeatedFields_, null);
};
goog.inherits(proto.msg.RoomListResp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.msg.RoomListResp.displayName = 'proto.msg.RoomListResp';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.msg.RoomListResp.RoomItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.msg.RoomListResp.RoomItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.msg.RoomListResp.RoomItem.displayName = 'proto.msg.RoomListResp.RoomItem';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.msg.RoomListResp.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.msg.RoomListResp.prototype.toObject = function(opt_includeInstance) {
  return proto.msg.RoomListResp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.msg.RoomListResp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg.RoomListResp.toObject = function(includeInstance, msg) {
  var f, obj = {
    itemsList: jspb.Message.toObjectList(msg.getItemsList(),
    proto.msg.RoomListResp.RoomItem.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.msg.RoomListResp}
 */
proto.msg.RoomListResp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.msg.RoomListResp;
  return proto.msg.RoomListResp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.msg.RoomListResp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.msg.RoomListResp}
 */
proto.msg.RoomListResp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.msg.RoomListResp.RoomItem;
      reader.readMessage(value,proto.msg.RoomListResp.RoomItem.deserializeBinaryFromReader);
      msg.addItems(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.msg.RoomListResp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.msg.RoomListResp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.msg.RoomListResp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg.RoomListResp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getItemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.msg.RoomListResp.RoomItem.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.msg.RoomListResp.RoomItem.prototype.toObject = function(opt_includeInstance) {
  return proto.msg.RoomListResp.RoomItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.msg.RoomListResp.RoomItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg.RoomListResp.RoomItem.toObject = function(includeInstance, msg) {
  var f, obj = {
    confid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    blind: jspb.Message.getFieldWithDefault(msg, 2, 0),
    mod: jspb.Message.getFieldWithDefault(msg, 3, 0),
    status: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.msg.RoomListResp.RoomItem}
 */
proto.msg.RoomListResp.RoomItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.msg.RoomListResp.RoomItem;
  return proto.msg.RoomListResp.RoomItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.msg.RoomListResp.RoomItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.msg.RoomListResp.RoomItem}
 */
proto.msg.RoomListResp.RoomItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setConfid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBlind(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMod(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.msg.RoomListResp.RoomItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.msg.RoomListResp.RoomItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.msg.RoomListResp.RoomItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg.RoomListResp.RoomItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getConfid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getBlind();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getMod();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
};


/**
 * optional int32 Confid = 1;
 * @return {number}
 */
proto.msg.RoomListResp.RoomItem.prototype.getConfid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.msg.RoomListResp.RoomItem.prototype.setConfid = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 Blind = 2;
 * @return {number}
 */
proto.msg.RoomListResp.RoomItem.prototype.getBlind = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.msg.RoomListResp.RoomItem.prototype.setBlind = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 Mod = 3;
 * @return {number}
 */
proto.msg.RoomListResp.RoomItem.prototype.getMod = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.msg.RoomListResp.RoomItem.prototype.setMod = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 Status = 4;
 * @return {number}
 */
proto.msg.RoomListResp.RoomItem.prototype.getStatus = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.msg.RoomListResp.RoomItem.prototype.setStatus = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * repeated RoomItem Items = 1;
 * @return {!Array<!proto.msg.RoomListResp.RoomItem>}
 */
proto.msg.RoomListResp.prototype.getItemsList = function() {
  return /** @type{!Array<!proto.msg.RoomListResp.RoomItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.msg.RoomListResp.RoomItem, 1));
};


/** @param {!Array<!proto.msg.RoomListResp.RoomItem>} value */
proto.msg.RoomListResp.prototype.setItemsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.msg.RoomListResp.RoomItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.msg.RoomListResp.RoomItem}
 */
proto.msg.RoomListResp.prototype.addItems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.msg.RoomListResp.RoomItem, opt_index);
};


proto.msg.RoomListResp.prototype.clearItemsList = function() {
  this.setItemsList([]);
};


