/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.msg.UpdateResp');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.msg.UpdateResp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.msg.UpdateResp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.msg.UpdateResp.displayName = 'proto.msg.UpdateResp';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.msg.UpdateResp.prototype.toObject = function(opt_includeInstance) {
  return proto.msg.UpdateResp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.msg.UpdateResp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg.UpdateResp.toObject = function(includeInstance, msg) {
  var f, obj = {
    regversion: jspb.Message.getFieldWithDefault(msg, 1, ""),
    apkurl: jspb.Message.getFieldWithDefault(msg, 2, ""),
    hoturl: jspb.Message.getFieldWithDefault(msg, 3, ""),
    pageurl: jspb.Message.getFieldWithDefault(msg, 4, ""),
    notice: jspb.Message.getFieldWithDefault(msg, 5, ""),
    curversion: jspb.Message.getFieldWithDefault(msg, 6, ""),
    updatemode: jspb.Message.getFieldWithDefault(msg, 7, 0),
    apkversion: jspb.Message.getFieldWithDefault(msg, 8, ""),
    packeturl: jspb.Message.getFieldWithDefault(msg, 9, ""),
    conf: jspb.Message.getFieldWithDefault(msg, 10, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.msg.UpdateResp}
 */
proto.msg.UpdateResp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.msg.UpdateResp;
  return proto.msg.UpdateResp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.msg.UpdateResp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.msg.UpdateResp}
 */
proto.msg.UpdateResp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRegversion(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setApkurl(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setHoturl(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPageurl(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setNotice(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setCurversion(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setUpdatemode(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setApkversion(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setPacketurl(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setConf(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.msg.UpdateResp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.msg.UpdateResp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.msg.UpdateResp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg.UpdateResp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRegversion();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getApkurl();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getHoturl();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPageurl();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getNotice();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getCurversion();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getUpdatemode();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getApkversion();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getPacketurl();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getConf();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
};


/**
 * optional string Regversion = 1;
 * @return {string}
 */
proto.msg.UpdateResp.prototype.getRegversion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.msg.UpdateResp.prototype.setRegversion = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string Apkurl = 2;
 * @return {string}
 */
proto.msg.UpdateResp.prototype.getApkurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.msg.UpdateResp.prototype.setApkurl = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string Hoturl = 3;
 * @return {string}
 */
proto.msg.UpdateResp.prototype.getHoturl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.msg.UpdateResp.prototype.setHoturl = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string Pageurl = 4;
 * @return {string}
 */
proto.msg.UpdateResp.prototype.getPageurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.msg.UpdateResp.prototype.setPageurl = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string Notice = 5;
 * @return {string}
 */
proto.msg.UpdateResp.prototype.getNotice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.msg.UpdateResp.prototype.setNotice = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string Curversion = 6;
 * @return {string}
 */
proto.msg.UpdateResp.prototype.getCurversion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.msg.UpdateResp.prototype.setCurversion = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional int32 Updatemode = 7;
 * @return {number}
 */
proto.msg.UpdateResp.prototype.getUpdatemode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.msg.UpdateResp.prototype.setUpdatemode = function(value) {
  jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional string Apkversion = 8;
 * @return {string}
 */
proto.msg.UpdateResp.prototype.getApkversion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.msg.UpdateResp.prototype.setApkversion = function(value) {
  jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string Packeturl = 9;
 * @return {string}
 */
proto.msg.UpdateResp.prototype.getPacketurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/** @param {string} value */
proto.msg.UpdateResp.prototype.setPacketurl = function(value) {
  jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string Conf = 10;
 * @return {string}
 */
proto.msg.UpdateResp.prototype.getConf = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/** @param {string} value */
proto.msg.UpdateResp.prototype.setConf = function(value) {
  jspb.Message.setProto3StringField(this, 10, value);
};


