/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.msg.ShopUserResp');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.msg.SkinUser');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.msg.ShopUserResp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.msg.ShopUserResp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.msg.ShopUserResp.displayName = 'proto.msg.ShopUserResp';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.msg.ShopUserResp.prototype.toObject = function(opt_includeInstance) {
  return proto.msg.ShopUserResp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.msg.ShopUserResp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg.ShopUserResp.toObject = function(includeInstance, msg) {
  var f, obj = {
    skills: jspb.Message.getFieldWithDefault(msg, 1, ""),
    frames: jspb.Message.getFieldWithDefault(msg, 2, ""),
    prop: jspb.Message.getFieldWithDefault(msg, 3, ""),
    nftprop: jspb.Message.getFieldWithDefault(msg, 4, ""),
    propfrag: jspb.Message.getFieldWithDefault(msg, 5, ""),
    curprop: (f = msg.getCurprop()) && proto.msg.SkinUser.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.msg.ShopUserResp}
 */
proto.msg.ShopUserResp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.msg.ShopUserResp;
  return proto.msg.ShopUserResp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.msg.ShopUserResp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.msg.ShopUserResp}
 */
proto.msg.ShopUserResp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSkills(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setFrames(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setProp(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setNftprop(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setPropfrag(value);
      break;
    case 6:
      var value = new proto.msg.SkinUser;
      reader.readMessage(value,proto.msg.SkinUser.deserializeBinaryFromReader);
      msg.setCurprop(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.msg.ShopUserResp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.msg.ShopUserResp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.msg.ShopUserResp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg.ShopUserResp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSkills();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFrames();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getProp();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getNftprop();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getPropfrag();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getCurprop();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.msg.SkinUser.serializeBinaryToWriter
    );
  }
};


/**
 * optional string Skills = 1;
 * @return {string}
 */
proto.msg.ShopUserResp.prototype.getSkills = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.msg.ShopUserResp.prototype.setSkills = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string Frames = 2;
 * @return {string}
 */
proto.msg.ShopUserResp.prototype.getFrames = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.msg.ShopUserResp.prototype.setFrames = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string Prop = 3;
 * @return {string}
 */
proto.msg.ShopUserResp.prototype.getProp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.msg.ShopUserResp.prototype.setProp = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string Nftprop = 4;
 * @return {string}
 */
proto.msg.ShopUserResp.prototype.getNftprop = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.msg.ShopUserResp.prototype.setNftprop = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string PropFrag = 5;
 * @return {string}
 */
proto.msg.ShopUserResp.prototype.getPropfrag = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.msg.ShopUserResp.prototype.setPropfrag = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional SkinUser Curprop = 6;
 * @return {?proto.msg.SkinUser}
 */
proto.msg.ShopUserResp.prototype.getCurprop = function() {
  return /** @type{?proto.msg.SkinUser} */ (
    jspb.Message.getWrapperField(this, proto.msg.SkinUser, 6));
};


/** @param {?proto.msg.SkinUser|undefined} value */
proto.msg.ShopUserResp.prototype.setCurprop = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.msg.ShopUserResp.prototype.clearCurprop = function() {
  this.setCurprop(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.msg.ShopUserResp.prototype.hasCurprop = function() {
  return jspb.Message.getField(this, 6) != null;
};


