/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.msg.ShopAllListResp');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.msg.ShopItem');
goog.require('proto.msg.SkillItem');
goog.require('proto.msg.SkinItem');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.msg.ShopAllListResp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.msg.ShopAllListResp.repeatedFields_, null);
};
goog.inherits(proto.msg.ShopAllListResp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.msg.ShopAllListResp.displayName = 'proto.msg.ShopAllListResp';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.msg.ShopAllListResp.repeatedFields_ = [1,2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.msg.ShopAllListResp.prototype.toObject = function(opt_includeInstance) {
  return proto.msg.ShopAllListResp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.msg.ShopAllListResp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg.ShopAllListResp.toObject = function(includeInstance, msg) {
  var f, obj = {
    shopitemsList: jspb.Message.toObjectList(msg.getShopitemsList(),
    proto.msg.ShopItem.toObject, includeInstance),
    skinitemsList: jspb.Message.toObjectList(msg.getSkinitemsList(),
    proto.msg.SkinItem.toObject, includeInstance),
    skillitemsList: jspb.Message.toObjectList(msg.getSkillitemsList(),
    proto.msg.SkillItem.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.msg.ShopAllListResp}
 */
proto.msg.ShopAllListResp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.msg.ShopAllListResp;
  return proto.msg.ShopAllListResp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.msg.ShopAllListResp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.msg.ShopAllListResp}
 */
proto.msg.ShopAllListResp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.msg.ShopItem;
      reader.readMessage(value,proto.msg.ShopItem.deserializeBinaryFromReader);
      msg.addShopitems(value);
      break;
    case 2:
      var value = new proto.msg.SkinItem;
      reader.readMessage(value,proto.msg.SkinItem.deserializeBinaryFromReader);
      msg.addSkinitems(value);
      break;
    case 3:
      var value = new proto.msg.SkillItem;
      reader.readMessage(value,proto.msg.SkillItem.deserializeBinaryFromReader);
      msg.addSkillitems(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.msg.ShopAllListResp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.msg.ShopAllListResp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.msg.ShopAllListResp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg.ShopAllListResp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getShopitemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.msg.ShopItem.serializeBinaryToWriter
    );
  }
  f = message.getSkinitemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.msg.SkinItem.serializeBinaryToWriter
    );
  }
  f = message.getSkillitemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.msg.SkillItem.serializeBinaryToWriter
    );
  }
};


/**
 * repeated ShopItem ShopItems = 1;
 * @return {!Array<!proto.msg.ShopItem>}
 */
proto.msg.ShopAllListResp.prototype.getShopitemsList = function() {
  return /** @type{!Array<!proto.msg.ShopItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.msg.ShopItem, 1));
};


/** @param {!Array<!proto.msg.ShopItem>} value */
proto.msg.ShopAllListResp.prototype.setShopitemsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.msg.ShopItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.msg.ShopItem}
 */
proto.msg.ShopAllListResp.prototype.addShopitems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.msg.ShopItem, opt_index);
};


proto.msg.ShopAllListResp.prototype.clearShopitemsList = function() {
  this.setShopitemsList([]);
};


/**
 * repeated SkinItem Skinitems = 2;
 * @return {!Array<!proto.msg.SkinItem>}
 */
proto.msg.ShopAllListResp.prototype.getSkinitemsList = function() {
  return /** @type{!Array<!proto.msg.SkinItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.msg.SkinItem, 2));
};


/** @param {!Array<!proto.msg.SkinItem>} value */
proto.msg.ShopAllListResp.prototype.setSkinitemsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.msg.SkinItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.msg.SkinItem}
 */
proto.msg.ShopAllListResp.prototype.addSkinitems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.msg.SkinItem, opt_index);
};


proto.msg.ShopAllListResp.prototype.clearSkinitemsList = function() {
  this.setSkinitemsList([]);
};


/**
 * repeated SkillItem Skillitems = 3;
 * @return {!Array<!proto.msg.SkillItem>}
 */
proto.msg.ShopAllListResp.prototype.getSkillitemsList = function() {
  return /** @type{!Array<!proto.msg.SkillItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.msg.SkillItem, 3));
};


/** @param {!Array<!proto.msg.SkillItem>} value */
proto.msg.ShopAllListResp.prototype.setSkillitemsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.msg.SkillItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.msg.SkillItem}
 */
proto.msg.ShopAllListResp.prototype.addSkillitems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.msg.SkillItem, opt_index);
};


proto.msg.ShopAllListResp.prototype.clearSkillitemsList = function() {
  this.setSkillitemsList([]);
};


