/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.msg.SkillItem');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

goog.forwardDeclare('proto.msg.EnSkillID');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.msg.SkillItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.msg.SkillItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.msg.SkillItem.displayName = 'proto.msg.SkillItem';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.msg.SkillItem.prototype.toObject = function(opt_includeInstance) {
  return proto.msg.SkillItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.msg.SkillItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg.SkillItem.toObject = function(includeInstance, msg) {
  var f, obj = {
    sid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    stype: jspb.Message.getFieldWithDefault(msg, 2, 0),
    sname: jspb.Message.getFieldWithDefault(msg, 3, ""),
    sicon: jspb.Message.getFieldWithDefault(msg, 4, ""),
    cdtime: jspb.Message.getFieldWithDefault(msg, 5, 0),
    durationtime: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.msg.SkillItem}
 */
proto.msg.SkillItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.msg.SkillItem;
  return proto.msg.SkillItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.msg.SkillItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.msg.SkillItem}
 */
proto.msg.SkillItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSid(value);
      break;
    case 2:
      var value = /** @type {!proto.msg.EnSkillID} */ (reader.readEnum());
      msg.setStype(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSname(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setSicon(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCdtime(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDurationtime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.msg.SkillItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.msg.SkillItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.msg.SkillItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg.SkillItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getStype();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getSname();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getSicon();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getCdtime();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getDurationtime();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
};


/**
 * optional int32 SID = 1;
 * @return {number}
 */
proto.msg.SkillItem.prototype.getSid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.msg.SkillItem.prototype.setSid = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional EnSkillID SType = 2;
 * @return {!proto.msg.EnSkillID}
 */
proto.msg.SkillItem.prototype.getStype = function() {
  return /** @type {!proto.msg.EnSkillID} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.msg.EnSkillID} value */
proto.msg.SkillItem.prototype.setStype = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string Sname = 3;
 * @return {string}
 */
proto.msg.SkillItem.prototype.getSname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.msg.SkillItem.prototype.setSname = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string SIcon = 4;
 * @return {string}
 */
proto.msg.SkillItem.prototype.getSicon = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.msg.SkillItem.prototype.setSicon = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int32 CDTime = 5;
 * @return {number}
 */
proto.msg.SkillItem.prototype.getCdtime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.msg.SkillItem.prototype.setCdtime = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 DurationTime = 6;
 * @return {number}
 */
proto.msg.SkillItem.prototype.getDurationtime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.msg.SkillItem.prototype.setDurationtime = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};


