/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.msg.SkinUser');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.msg.SkinUser = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.msg.SkinUser, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.msg.SkinUser.displayName = 'proto.msg.SkinUser';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.msg.SkinUser.prototype.toObject = function(opt_includeInstance) {
  return proto.msg.SkinUser.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.msg.SkinUser} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg.SkinUser.toObject = function(includeInstance, msg) {
  var f, obj = {
    usid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    skinid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    use: jspb.Message.getFieldWithDefault(msg, 3, 0),
    sname: jspb.Message.getFieldWithDefault(msg, 4, ""),
    max: jspb.Message.getFieldWithDefault(msg, 5, 0),
    turn: jspb.Message.getFieldWithDefault(msg, 6, 0),
    cur: jspb.Message.getFieldWithDefault(msg, 7, 0),
    utime: jspb.Message.getFieldWithDefault(msg, 8, 0),
    skillid: jspb.Message.getFieldWithDefault(msg, 9, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.msg.SkinUser}
 */
proto.msg.SkinUser.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.msg.SkinUser;
  return proto.msg.SkinUser.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.msg.SkinUser} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.msg.SkinUser}
 */
proto.msg.SkinUser.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setUsid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSkinid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setUse(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setSname(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMax(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTurn(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCur(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUtime(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSkillid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.msg.SkinUser.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.msg.SkinUser.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.msg.SkinUser} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg.SkinUser.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUsid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getSkinid();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getUse();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getSname();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getMax();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getTurn();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getCur();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getUtime();
  if (f !== 0) {
    writer.writeInt64(
      8,
      f
    );
  }
  f = message.getSkillid();
  if (f !== 0) {
    writer.writeInt32(
      9,
      f
    );
  }
};


/**
 * optional int32 USid = 1;
 * @return {number}
 */
proto.msg.SkinUser.prototype.getUsid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.msg.SkinUser.prototype.setUsid = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 SkinID = 2;
 * @return {number}
 */
proto.msg.SkinUser.prototype.getSkinid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.msg.SkinUser.prototype.setSkinid = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 Use = 3;
 * @return {number}
 */
proto.msg.SkinUser.prototype.getUse = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.msg.SkinUser.prototype.setUse = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string SName = 4;
 * @return {string}
 */
proto.msg.SkinUser.prototype.getSname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.msg.SkinUser.prototype.setSname = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int32 Max = 5;
 * @return {number}
 */
proto.msg.SkinUser.prototype.getMax = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.msg.SkinUser.prototype.setMax = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 Turn = 6;
 * @return {number}
 */
proto.msg.SkinUser.prototype.getTurn = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.msg.SkinUser.prototype.setTurn = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int32 Cur = 7;
 * @return {number}
 */
proto.msg.SkinUser.prototype.getCur = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.msg.SkinUser.prototype.setCur = function(value) {
  jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int64 UTime = 8;
 * @return {number}
 */
proto.msg.SkinUser.prototype.getUtime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/** @param {number} value */
proto.msg.SkinUser.prototype.setUtime = function(value) {
  jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional int32 Skillid = 9;
 * @return {number}
 */
proto.msg.SkinUser.prototype.getSkillid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {number} value */
proto.msg.SkinUser.prototype.setSkillid = function(value) {
  jspb.Message.setProto3IntField(this, 9, value);
};


