/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.msg.SkinItem');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

goog.forwardDeclare('proto.msg.EnShopType');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.msg.SkinItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.msg.SkinItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.msg.SkinItem.displayName = 'proto.msg.SkinItem';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.msg.SkinItem.prototype.toObject = function(opt_includeInstance) {
  return proto.msg.SkinItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.msg.SkinItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg.SkinItem.toObject = function(includeInstance, msg) {
  var f, obj = {
    skinid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    stype: jspb.Message.getFieldWithDefault(msg, 2, 0),
    sname: jspb.Message.getFieldWithDefault(msg, 3, ""),
    sicon: jspb.Message.getFieldWithDefault(msg, 4, ""),
    skillid: jspb.Message.getFieldWithDefault(msg, 5, 0),
    fragid: jspb.Message.getFieldWithDefault(msg, 6, 0),
    fragnum: jspb.Message.getFieldWithDefault(msg, 7, 0),
    combid: jspb.Message.getFieldWithDefault(msg, 8, 0),
    sgenaim: jspb.Message.getFieldWithDefault(msg, 9, ""),
    smaxpower: jspb.Message.getFieldWithDefault(msg, 10, 0),
    sturnpower: jspb.Message.getFieldWithDefault(msg, 11, 0),
    ssource: jspb.Message.getFieldWithDefault(msg, 12, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.msg.SkinItem}
 */
proto.msg.SkinItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.msg.SkinItem;
  return proto.msg.SkinItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.msg.SkinItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.msg.SkinItem}
 */
proto.msg.SkinItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSkinid(value);
      break;
    case 2:
      var value = /** @type {!proto.msg.EnShopType} */ (reader.readEnum());
      msg.setStype(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSname(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setSicon(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSkillid(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFragid(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFragnum(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCombid(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setSgenaim(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSmaxpower(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSturnpower(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setSsource(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.msg.SkinItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.msg.SkinItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.msg.SkinItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg.SkinItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSkinid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getStype();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getSname();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getSicon();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getSkillid();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getFragid();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getFragnum();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getCombid();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = message.getSgenaim();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getSmaxpower();
  if (f !== 0) {
    writer.writeInt32(
      10,
      f
    );
  }
  f = message.getSturnpower();
  if (f !== 0) {
    writer.writeInt32(
      11,
      f
    );
  }
  f = message.getSsource();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
};


/**
 * optional int32 SkinID = 1;
 * @return {number}
 */
proto.msg.SkinItem.prototype.getSkinid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.msg.SkinItem.prototype.setSkinid = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional EnShopType Stype = 2;
 * @return {!proto.msg.EnShopType}
 */
proto.msg.SkinItem.prototype.getStype = function() {
  return /** @type {!proto.msg.EnShopType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.msg.EnShopType} value */
proto.msg.SkinItem.prototype.setStype = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string Sname = 3;
 * @return {string}
 */
proto.msg.SkinItem.prototype.getSname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.msg.SkinItem.prototype.setSname = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string Sicon = 4;
 * @return {string}
 */
proto.msg.SkinItem.prototype.getSicon = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.msg.SkinItem.prototype.setSicon = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int32 Skillid = 5;
 * @return {number}
 */
proto.msg.SkinItem.prototype.getSkillid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.msg.SkinItem.prototype.setSkillid = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 Fragid = 6;
 * @return {number}
 */
proto.msg.SkinItem.prototype.getFragid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.msg.SkinItem.prototype.setFragid = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int32 Fragnum = 7;
 * @return {number}
 */
proto.msg.SkinItem.prototype.getFragnum = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.msg.SkinItem.prototype.setFragnum = function(value) {
  jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int32 CombID = 8;
 * @return {number}
 */
proto.msg.SkinItem.prototype.getCombid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/** @param {number} value */
proto.msg.SkinItem.prototype.setCombid = function(value) {
  jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional string SgenAim = 9;
 * @return {string}
 */
proto.msg.SkinItem.prototype.getSgenaim = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/** @param {string} value */
proto.msg.SkinItem.prototype.setSgenaim = function(value) {
  jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional int32 SMaxPower = 10;
 * @return {number}
 */
proto.msg.SkinItem.prototype.getSmaxpower = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/** @param {number} value */
proto.msg.SkinItem.prototype.setSmaxpower = function(value) {
  jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional int32 STurnPower = 11;
 * @return {number}
 */
proto.msg.SkinItem.prototype.getSturnpower = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/** @param {number} value */
proto.msg.SkinItem.prototype.setSturnpower = function(value) {
  jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional string Ssource = 12;
 * @return {string}
 */
proto.msg.SkinItem.prototype.getSsource = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/** @param {string} value */
proto.msg.SkinItem.prototype.setSsource = function(value) {
  jspb.Message.setProto3StringField(this, 12, value);
};


